SELECT R.AUTHOR_ID, R.AUTHOR_NAME, R.CATEGORY, SUM(T) AS TOTAL_SALES
FROM (SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (B.PRICE * SUM(S.SALES)) AS T
     FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE < '2022-02-01'
    GROUP BY B.AUTHOR_ID, B.CATEGORY, B.BOOK_ID
     ) AS R
GROUP BY R.AUTHOR_ID, R.CATEGORY
ORDER BY R.AUTHOR_ID ASC, R.CATEGORY DESC;

