SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30 * (100 - DISCOUNT_RATE) * 0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (SELECT DISTINCT H2.CAR_ID 
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H2
                       WHERE H2.START_DATE <= '2022-11-30' AND H2.END_DATE >= '2022-11-01')
AND P.DURATION_TYPE = '30일 이상'
AND C.DAILY_FEE * 30 * (100 - DISCOUNT_RATE) * 0.01 >= 500000 AND C.DAILY_FEE * 30 * (100 - DISCOUNT_RATE) * 0.01 < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
