SELECT DISTINCT k.CAR_ID, p.CAR_TYPE, TRUNCATE(k.DAILY_FEE * 30 * ((100 - DISCOUNT_RATE) / 100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
JOIN (
    SELECT c.CAR_ID, c.CAR_TYPE, c.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h on c.CAR_ID = h.CAR_ID
    where CAR_TYPE IN ('SUV', '세단')
    AND NOT EXISTS (
        SELECT *
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
        WHERE h.CAR_ID = c.CAR_ID
          AND h.START_DATE <= '2022-11-30'
          AND h.END_DATE   >= '2022-11-01'
      )
    ) k on k.CAR_TYPE = p.CAR_TYPE AND DURATION_TYPE = '30일 이상'
where (k.DAILY_FEE * 30 * (100 - DISCOUNT_RATE)/100) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, p.CAR_TYPE ASC, k.CAR_ID DESC;