SELECT r.FOOD_TYPE, r.REST_ID, r.REST_NAME, r.FAVORITES
FROM (
    SELECT i.FOOD_TYPE, i.REST_ID, i.REST_NAME, i.FAVORITES,
    RANK() OVER (PARTITION BY i.FOOD_TYPE ORDER BY i.FAVORITES DESC) AS RR
    FROM REST_INFO i
    ) r
    WHERE RR = 1
ORDER BY r.FOOD_TYPE desc;