-- 코드를 입력하세요
SELECT DISTINCT c.CAR_ID
From CAR_RENTAL_COMPANY_CAR c
Join CAR_RENTAL_COMPANY_RENTAL_HISTORY h on c.CAR_ID = h.CAR_ID
where h.START_DATE >= '2022-10-01'
AND h.START_DATE < '2022-11-01' AND CAR_TYPE = '세단'
order by c.CAR_ID DESC;